### ISSUE TITLE
Support for Shelly Plus 2PM

### ISSUE THREAD

**Issue by herzkerl** [mongoose-os-apps/shelly-homekit#1013] opened 2022-06-15 17:05 UTC
I couldn‘t find any comments regarding the Plus 2PM, is there any news regarding this device?

**Comment by jonasman** [comment] 2022-06-19 14:42
I also need this

**Comment by Sorbat** [comment] 2022-07-15 17:41
is there anything new here? can you already say when an alpha/beta version will be available or is planned?

Thank you very much

**Comment by 1974here** [comment] 2022-08-02 11:55
Same here.. longing for a plus2 firmware. 🙂

**Comment by MagOO33** [comment] 2022-08-03 20:56
Hello, Shelly 2.5 is replaced by Shelly 2PM by resellers in my country because 2.5 has too many hardware problems. It would be very nice to have a mongoose support for this new shelly.

**Comment by firstusing** [comment] 2022-08-08 20:57
Same here, could only get "plus 2pm´s" for my covers. 
I would too be happy to have a Firmware for it.

**Comment by c4ris** [comment] 2022-08-28 06:39
a firmware would be nice

**Comment by AG-dingoant** [comment] 2022-08-29 11:51
I just installed a Shelly 2 Plus. I would really like to have the firmware as well :-)

**Comment by rojer** [comment] 2022-08-30 21:19
working on it, stay tuned

**Comment by aqzsed123456** [comment] 2022-09-05 18:03
Hello Rojer, what shelly plus 2 PM will solve problem #985? Thank you very much.

**Comment by rojer** [comment] 2022-09-08 01:53
who knows, maybe if it's to do with power measurement somehow. though Plus2PM uses the same power measurement chip, so it's unlikely.

**Comment by aqzsed123456** [comment] 2022-09-08 09:49
Hello rojer, when I do not flash the shelly 2.5 my two large roller shutters work very well with the shelly application on the other hand when I flash them "HomeKit" the calibration hurts so the roller shutters do not close completely. Is it possible to solve this problem by putting a corrective update on shelly 2.5 or to do it on shelly plus 2PM? So that I know if I have to wait for the update of shelly 2.5 or if I need to buy shelly plus 2PM? Thank you very much

**Comment by solitpapa** [comment] 2022-09-19 21:51
hi, as my 1st from 9 shellys 2.5 after almost 2 years of using starts to die I probably need to start thinking about change to 2PM.
I also would appreciate the introduction of your firmware for that device.

**Comment by azuma82** [comment] 2022-10-02 09:52
Hello, I have also the new +2PM an will use it for optimized my fans system with the netatmo Wetterstation in Applehome. Thanks for you're work on it

**Comment by andybenichou** [comment] 2022-10-16 15:42
Hi, thank you for your work it is amazing !! Sorry to ask but do you think the Shelly Plus 2PM will be supported soon, I am using homebridge now but it is not working well? Thank you!

**Comment by jonasman** [comment] 2022-10-19 11:24
Gosh, my shellys 2.5PMs are all dying and im replacing with the new 2PM plus. Hopefully this could come soon :)

**Comment by jonasman** [comment] 2022-12-11 23:40
Hi!
any update on this? any beta version to try?

**Comment by Rickth64** [comment] 2022-12-28 17:37
Would love to see this

**Comment by rsalesas** [comment] 2023-01-02 12:46
I have a 2.5 that works great for my awning, was going to deploy more for my shutters, but see that the 2PM is not supported. Happy to help testing...

**Comment by bjoerrrn** [comment] 2023-01-07 15:13
looking forward to Shelly Plus 2PM support, too

**Comment by tcdsantos** [comment] 2023-01-09 22:36
Hi!
Is this project alive? Are there any plans to add support for Shelly Plus 2PM ?
Thank you.

**Comment by luisfernandes88** [comment] 2023-01-13 22:38
One more 😀 we need this !

**Comment by WeisserWolf611** [comment] 2023-01-20 20:35
I think there will never come an Homekit-Image. Shelly will support matter and apple will support matter. So why waste time?!

**Comment by WeisserWolf611** [comment] 2023-01-20 22:02
All my 2.5 died, so i replaced all with plus 2PM, but it is not working similar and I cant send it back to Allterco, so I have to wait for matter 🤷🏼‍♂️

**Comment by luisfernandes88** [comment] 2023-01-20 22:08
> I think there will never come an Homekit-Image. Shelly will support matter and apple will support matter. So why waste time?!

Where did you see that info ? Shelly will support matter ?

**Comment by Rickth64** [comment] 2023-01-20 22:39
> > I think there will never come an Homekit-Image. Shelly will support matter and apple will support matter. So why waste time?!
> 
> Where did you see that info ? Shelly will support matter ?

https://www.reddit.com/r/shellycloud/comments/10a8bk7/finally_confirmed_matter_support/

**Comment by timoschilling** [comment] 2023-01-20 23:21
There are still reasons why we will continue to work on this firmware. First matter didn't support all things we do in HomeKit. And how knows that matter support for shelly really comes? They already announced HomeKit support for the plus models and it never happened.

**Comment by WeisserWolf611** [comment] 2023-01-21 05:04
> > I think there will never come an Homekit-Image. Shelly will support matter and apple will support matter. So why waste time?!
> 
> Where did you see that info ? Shelly will support matter ?

Official answer ofrom Allterco:
Thank you for contacting us!
We are working on the Matter support.
But only for Plus and Pro series.

**Comment by harrisonkohn** [comment] 2023-01-21 06:00
Do we have any news on update for this any time soon? Is a unit needed to test?

**Comment by davidjbradshaw** [comment] 2023-01-23 15:06
@harrisonkohn the other week they said June/July.

**Comment by timoschilling** [comment] 2023-01-23 20:13
Please don’t discuss over matter support for the stock firmware here, that’s offtopic

**Comment by timoschilling** [comment] 2023-01-27 09:41
I made some progress, but now I bricked my dev Plus2PM :(

**Comment by 5xPa** [comment] 2023-01-27 10:41
I would be happy to donate £25 to permit you to purchase a replacement. If you provide a link

**Comment by Rickth64** [comment] 2023-01-27 10:59
I was about to say the same. Let us know so you have a few to brick :-)

**Comment by timoschilling** [comment] 2023-01-27 11:55
https://paypal.me/timoschilling

**Comment by timoschilling** [comment] 2023-01-27 11:55
That would be nice https://paypal.me/timoschilling

**Comment by 5xPa** [comment] 2023-01-27 12:10
Timo have made the donation a small token of my appreciation of the work on
the project.
If for any reason the funds do not show up please let me know

**Comment by 1974here** [comment] 2023-01-27 15:50
+1Thanks for working on this project, Timo!!//HeikoVon meinem iPhone gesendetAm 27.01.2023 um 16:24 schrieb Hugo Francisco ***@***.***>:﻿
+1

**Comment by duskiez** [comment] 2023-01-30 10:03
need this as well and will send a donation - thanks for working on this

**Comment by timoschilling** [comment] 2023-02-03 21:55
Short update: I get HomeKit working on the 2PM. But now I burned my flasher and one of my Mac Book USB ports 🤦‍♂️. Open points are revertible to stock and power measurement.

**Comment by jonasman** [comment] 2023-02-03 23:10
How did you burn the usb??

**Comment by duskiez** [comment] 2023-02-03 23:29
> Short update: I get HomeKit working on the 2PM. But now I burned my flasher and one of my Mac Book USB ports 🤦‍♂️. Open points are revertible to stock and power measurement.

Awesome, can’t wait for the release!

**Comment by rsalesas** [comment] 2023-02-04 14:48
Really sorry you lost the port - is it repairable? Happy to contribute to compensate.

**Comment by timoschilling** [comment] 2023-02-08 11:02
I was testing with the power measurement, so the Shelly was connected to main power and I miss wired my flasher, I forgot to plug the voltage isolator between the flasher and the Shelly. So the 230V from main went into the flasher. That killed the Shelly, the flasher and one of my USB ports. I think repeating would mean to replace the main board.

**Comment by rsalesas** [comment] 2023-02-08 11:13
I don't think my contribution will cover that unfortunately! 😔

**Comment by Ioan-Popovici** [comment] 2023-02-13 12:55
> I was testing with the power measurement, so the Shelly was connected to main power and I miss wired my flasher, I forgot to plug the voltage isolator between the flasher and the Shelly. So the 230V from main went into the flasher. That killed the Shelly, the flasher and one of my USB ports. I think repeating would mean to replace the main board.

Unfortunate, but you should be able to replace the burned controller and port at a shop that still does hardware repair. Don't throw away the board yet ;)

Try to see if you can find someone in your area, it should be pretty cheap.

**Comment by timoschilling** [comment] 2023-02-16 21:00
I worked on it, switch and garage door worked fine, but revertible to stock and power measurement are still open issues.

**Comment by rsalesas** [comment] 2023-02-16 21:15
I would take those restrictions! Nice work!!

**Comment by rsalesas** [comment] 2023-02-16 21:16
Not sure how else to send this but... I would definable buy all my Shelley's on Amazon through an associate link. Would compensate you for all the amazing work.

**Comment by Captain-Chaos13** [comment] 2023-03-05 14:58
@timoschilling: i‘m waiting too😉 hope you are successful!

**Comment by smuel09** [comment] 2023-03-19 17:11
Hi @timoschilling Thank you for your hard work.
Is there an option to install other Shelly firmware on the plus2PM for the time being or it doesn't work like that?

**Comment by antoine4livre** [comment] 2023-04-21 17:11
+1 It would be amazing ! 🙏

**Comment by sebr5884** [comment] 2023-04-21 17:34
Any updates on this? Is a firmware available now?

**Comment by failbit** [comment] 2023-05-03 16:27
Would really love this aswell!!

**Comment by TheBigNeo** [comment] 2023-05-05 09:48
I already had to replace 2 Shelly 2.5 this month. Yesterday the third died and now the 2.5 are no longer available. :(

**Comment by Sorbat** [comment] 2023-05-05 09:54
> I already had to replace 2 Shelly 2.5 this month. Yesterday the third died and now the 2.5 are no longer available. :(
I found some on amazon.fr last week https://www.amazon.it/dp/B08YNVSBSS/

**Comment by Sorbat** [comment] 2023-05-05 09:55
> > I already had to replace 2 Shelly 2.5 this month. Yesterday the third died and now the 2.5 are no longer available. :(
I found some on amazon.fr last week https://www.amazon.it/dp/B08YNVSBSS/

**Comment by tillmanz-valooba** [comment] 2023-05-16 08:05
Hi there!
Just checking in on how things are progressing. :-) 
Apart from my financial contribution is there anything additionally that I could possibly do to support @timoschilling or @rojer with this?

**Comment by CincoD2** [comment] 2023-06-02 07:24
Also waiting this, @rojer ! I'd contribute to get it!

**Comment by Tillman-Z** [comment] 2023-06-02 07:57
Hi @timoschilling 😀 It would be great if you could share some info on the current state of the Plus 2PM support. Are you still working on it?

**Comment by sebsi1** [comment] 2023-06-03 21:13
Need it too :/

**Comment by thatslolo** [comment] 2023-06-03 22:26
Just so you know: You can use the Tasmota FW on the Shelly Plus 2 PM with Matter and integrate it natively in Apple Home.

https://tasmota.github.io/docs/Matter/

**Comment by hughfr4nc15** [comment] 2023-06-04 07:50
> Just so you know: You can use the Tasmota FW on the Shelly Plus 2 PM with Matter and integrate it natively in Apple Home.
> 
> 
> 
> https://tasmota.github.io/docs/Matter/

Isn't Shelly gonna release native firmware with matter support for the Plus devices soon?

**Comment by jonasman** [comment] 2023-06-04 20:54
@hughfr4nc15 yes they will. the CTO mentions on reddit Q2, possibly Q3 

However since i dont like to wait, i installed a raspberry PI with Homebridge and my shellies are all on homekit now. Plus you get the native shelly app to count energy

**Comment by timoschilling** [comment] 2023-06-05 14:56
Sorry brows no news form my site, I worked on it for multiple weeks in the last months, but I can't resolve the problems.
The open problems are:
1. revert to stock didn't work
2. power measurement didn't work
3. revision detection (there at least two hardware revision out there, with different pinouts)

**Comment by hughfr4nc15** [comment] 2023-06-05 15:17
@jonasman I actually have used the plug-in back when the Shelly Duo's were not supported by this firmware.
Are the Shelly Plus 2PM supported? Can't find them in the list of supported devices.

**Comment by jtowe1** [comment] 2023-06-28 12:33
> @hughfr4nc15 yes they will. the CTO mentioned on reddit Q2, possibly Q3 2023
> 
> However since i dont like to wait, i installed a raspberry PI with Homebridge and my shellies are all on homekit now. Plus you get the native shelly app to count energy

Thanks for this!  I already had homebridge working but didn't realize there was a plugin.  I'm now using it instead of this firmware.

**Comment by Psycoribble** [comment] 2023-07-10 16:55
> Sorry brows no news form my site, I worked on it for multiple weeks in the last months, but I can't resolve the problems. The open problems are:
> 
> 1. revert to stock didn't work
> 2. power measurement didn't work
> 3. revision detection (there at least two hardware revision out there, with different pinouts)

Hope u can solve these Problems. I want to use my new Shelly 2 PM for my Roller Shutters

**Comment by jonasman** [comment] 2023-07-13 15:02
@hughfr4nc15 there are 2 plugins, one for the gen 1 and another for gen 2
here's the gen 2 plugin: https://github.com/alexryd/homebridge-shelly-ng/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by hughfr4nc15** [comment] 2023-07-13 15:54
Yes. Actually noticed that yesterday!Thanks.On 13 Jul 2023, at 16:02, João Nunes ***@***.***> wrote:﻿
@hughfr4nc15 there are 2 plugins, one for the gen 1 and another for gen 2
here's the gen 2 plugin: https://github.com/alexryd/homebridge-shelly-ng/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by lieberjott** [comment] 2023-07-25 14:05
Really hope that the problems can be solved, as some of my Shelly 2.5 are dying too :(
Did also send some little money in order to support the great effort.

**Comment by digaus** [comment] 2023-08-01 14:22
"SNSW-002P16EU" and "SNSW-102P16EU" are the two revisions

**Comment by Alcor72** [comment] 2023-08-06 11:56
> Really hope that the problems can be solved, as some of my Shelly 2.5 are dying too :(
> Did also send some little money in order to support the great effort.

Same here… all my Shelly 2.5 are dying after 2 years of good job. 
Hope that the new version will be more reliable with the ease of the HomeKit firmware inside… that would be the perfect roller shutter relay!

**Comment by hughfr4nc15** [comment] 2023-08-06 13:12
I already started installing Plus 2PM's and integrating them in Homekit via Homebridge.

**Comment by DenisKost** [comment] 2023-08-06 14:31
+1 
Would love to know what's the ETA on this!

**Comment by solitpapa** [comment] 2023-08-09 23:02
can't wait for your update for shelly 2pm, as solution with Homebridge is not perfect. :(
missing points:
_+ The percentage and status are not updating well when we don't fully open/close the roller shutter with the wall switch
+ when the roller is closing/opening another click on the icon on the Home app does not stop the roller but starts moving in the inverse direction?_

all above is working perfect on 2.5 with your firmware.

**Comment by dennisherzing** [comment] 2023-08-21 08:51
Hi ,
is there any news on supporting Plus 2PM? thank you

**Comment by desek90** [comment] 2023-08-21 10:08
Hi,
I would also like to know if there is any news on that. I would highly appreciate Plus 2PM support!

**Comment by dodvip123** [comment] 2023-08-30 07:14
did anyone try this already?
https://www.youtube.com/watch?v=1VA9xkROiQc&ab_channel=RavenSystem

**Comment by dennisherzing** [comment] 2023-08-30 08:20
this looks interesting, lets give it a try ;-) thank you

**Comment by dodvip123** [comment] 2023-08-30 08:33
let us know how it goes! I'm planning to buy the Plus 2PM in the future so cannot test yet

**Comment by hughfr4nc15** [comment] 2023-08-30 09:46
I'm using Homebridge at the moment to make this work, because I was already using it for different accessories so that was simple, but, why not wait for the official firmware with Matter support? Shouldn't take that long to release I believe.

**Comment by vek030** [comment] 2023-09-05 15:10
Please Support this Shelly

**Comment by hejsiri** [comment] 2023-10-02 20:46
I am working on a project that will allow the garage door to be opened from a web browser on The Display Tesla cars. Shelly 2.5 works great in HomeKit as a garage door because it has the ability to connect 2 opening sensors. Using two sensors is the only smart solution to make it work just fine. The problem is that Shelly 2.5 is no longer sold. 
Maybe it would be worthwhile to release a beta version of the mongoose software for Shelly 2PM without the features that are not yet completed? For me, and I'm sure for many people here, it would be valuable if it worked at least as a simple switch and garage door opener. I would be happy and could continue working on my project. For the moment I don't know whether to look for another way or, however, to base the project on Shelly 2PM.

![garage-Tesla-Y-opening-3-Current-View](https://github.com/mongoose-os-apps/shelly-homekit/assets/37380727/50211b00-5194-4b52-8a09-ac5e8f660240)

**Comment by hejsiri** [comment] 2023-10-12 21:42
Referring to the control of the garage door.... is it possible to connect two opening sensors to Shelly Plus 1 or Shelly Plus 1PM with HomeKit software?

**Comment by hejsiri** [comment] 2023-10-18 07:37
Byłoby wspaniale, aby oprogramowanie Shelly 2PM miało chociaż funkcję otwierania bramy garażowej z 2 czujnikami otwarcia, dokładnie tak samo jak Shelly 2.5. Wiele osób na to czeka. Pomiar prądu jest dla mnie mało ważną funkcją. Przypominam, że Shelly 2.5 jest niedostępny w sprzedaży.

**Comment by solitpapa** [comment] 2023-10-18 07:46
Personally I would love to have control of roller shutter similar as 2.5. As 2.5 are dying one by one in my system, there is no worthy alternative. So having beta version capable to manage the above will be more than welcome. Timo - I keep finger crossed for finding some kind of solution to release beta.

**Comment by hejsiri** [comment] 2023-10-18 07:48
> From my perspective and I assume that many others power management is not crucial feature. Backflash to stock will be worth to have, but based on my experience - once flashed to your OS the coming back to stock is not needed, as long as shelly homekit os will follow to updates of homekit. Im really interested in having possibility to update my 2pm to beta version with mentioned cons.

I, too, am willing to forgo a return to the original software, provided there is an OTA update option in Shelly-Homekit for 2PM.

**Comment by MartinMuehlner** [comment] 2023-10-22 21:44
> To answer the beta / preview question: It would be possible, but it maybe results in a device which never can be backflashed to stock. That's a to hard point in my view. Expect because I can't guarantee that the power measuring will be solved in the future.

I would not need Power Measuring - just the same functions as 2,5 and I am good to go;) (using it as roller shutter, but since the "old" ones are dying I already swapped two to the 2pm)

**Comment by solitpapa** [comment] 2023-10-23 11:41
> Using it a s roller shutter would not work with the current state of the +2PM. Roller shutter requires power measurement.

Damn, this is unfortunately not good news... is there any chance that the development of 2pm will be continued to try to sort out the power management issue?

**Comment by thebobx** [comment] 2023-10-23 11:49
I am in the same situation, my 2.5 are dying and I didn't find a similar module (Wifi + homekit) for my roller shutters. So really hopping for the support of the 2pm here. Thanks.

**Comment by hughfr4nc15** [comment] 2023-10-23 12:45
> I am in the same situation, my 2.5 are dying and I didn't find a similar module (Wifi + homekit) for my roller shutters. So really hopping for the support of the 2pm here. Thanks.

I already started installing Plus 2PM's and integrating them in Homekit via Homebridge.

**Comment by thebobx** [comment] 2023-10-23 13:32
Do you use "homebridge-shelly-ng" ? Reading github issues it seams that 2PM are not working properly with physical buttons, is it ok for you ?

**Comment by hughfr4nc15** [comment] 2023-10-23 13:43
> Do you use "homebridge-shelly-ng" ? Reading github issues it seams that 2PM are not working properly with physical buttons, is it ok for you ?

Yep. Mine are working properlly... via Homekit, physical or Shelly app.

**Comment by solitpapa** [comment] 2023-10-23 19:01
> > Do you use "homebridge-shelly-ng" ? Reading github issues it seams that 2PM are not working properly with physical buttons, is it ok for you ?
> 
> Yep. Mine are working properlly... via Homekit, physical or Shelly app.

Dont you have following issues? 
- The percentage and status are not updating well when we don't fully open/close the roller shutter with the wall switch
- when the roller is closing/opening another click on the icon on the Home app does not stop the roller but starts moving in the inverse direction

These are cons which I discovered, as I also have one 2PM with homebridge

**Comment by hughfr4nc15** [comment] 2023-10-23 19:25
Yes, I have both... Not a big deal though (for me at least). If you ask Siri to set the shade at a xx% it will work.

**Comment by knabalex** [comment] 2023-11-15 06:22
Same problem ... my shellys 2.5 are dying and there is no device which can replace the roller shutter function ... returning to original software (Backflash) is not a necessary feature

**Comment by Elehiggle** [comment] 2023-11-15 13:11
> Same problem ... my shellys 2.5 are dying and there is no device which can replace the roller shutter function ... returning to original software (Backflash) is not a necessary feature

I just use Eve Shutter Switches everywhere now, you could also bury them inside the wall if you wanted.

**Comment by knabalex** [comment] 2023-11-15 16:35
Eve Shutter Switches didn’t match the design of my other switches in the house 😢Am 15.11.2023 um 14:11 schrieb Elehiggle ***@***.***>:﻿

Same problem ... my shellys 2.5 are dying and there is no device which can replace the roller shutter function ... returning to original software (Backflash) is not a necessary feature

I just use Eve Shutter Switches everywhere now, you could also bury them inside the wall if you wanted.

**Comment by Roalkege** [comment] 2023-11-28 12:02
> Using it a s roller shutter would not work with the current state of the +2PM. Roller shutter requires power measurement.

Correct me if i'm wrong but the Shelly Plus 2PM has integrated power measurement.
`2 relay outputs with power measurement on screw terminal`.
https://kb.shelly.cloud/knowledge-base/shelly-plus-2pm#ShellyPlus2PM(SNSW-002P16EU)-Shortdescription
https://www.shelly.com/de/products/shop/shelly-plus-2-pm/shelly-plus-2-pm-2-pack

**Comment by timoschilling** [comment] 2023-11-28 14:16
With the current state of our firmware it will not work to support window covers. The hardware support power measurement, but our firmware not.

**Comment by basejumpa** [comment] 2023-12-01 15:26
See #1341 with my build which works for lights.

**Comment by masip85** [comment] 2023-12-02 13:27
> With the current state of our firmware it will not work to support window covers. The hardware support power measurement, but our firmware not.

But, because it's not prepare to get the measurement or because it is impossible?

**Comment by ingski** [comment] 2023-12-09 15:18
> Using it a s roller shutter would not work with the current state of the +2PM. Roller shutter requires power measurement.

not necessarily - as I remember this is currently used to auto calibrate the opening and closing times. This could however be substituted by manual measuring of the times. I could live with that, although of course the downside would be a less accurate setting of intermediate positions.

Actually I'm using the special version from https://github.com/mongoose-os-apps/shelly-homekit/pull/449 in one of my 2.5 Shellys where due to a separate relay power measurement does not allow to identify the end positions. 
However - I am glad to get all three connected roller shutters fully opened and closed and I can well live with the vague setting I get when I set them to 20, 50 or 75% .

I believe a +2PM Version with the above patch integrated would be a good solution if you need to replace 2.5 devices...

**Comment by NS-K** [comment] 2023-12-17 18:51
@timoschilling 
I was taking a look to your plus2pm branch and something took my attention about the ade7953 initialisation on shelly 2PM+:
`int reset_pin = 33;
  mgos_gpio_set_mode(reset_pin, MGOS_GPIO_MODE_OUTPUT);
  mgos_gpio_write(reset_pin, 0);
  mgos_msleep(100);
  mgos_gpio_write(reset_pin, 1);
  mgos_gpio_set_mode(reset_pin, MGOS_GPIO_MODE_INPUT);` 

i see that you are resetting the pin 33 before the i2c communication which is the I2C SDA GPIO so i assume that you are working on the v0.1.5 hardware revision. but did you try to reconfigure the GPIO36 to INPUT mode as it's directly connected to the ADE7953's IRQ pin on this hardware revision. this will avoid any conflict like on the shelly25.

`
s_ade7953 = mgos_ade7953_create(mgos_i2c_get_global(), &ade7953_cfg);

  if (s_ade7953 == nullptr) {
    LOG(LL_INFO, ("Failed to init ADE7953"));
    return mgos::Errorf(STATUS_UNAVAILABLE, "Failed to init ADE7953");
  }

  Status st;
  std::unique_ptr<PowerMeter> pm1(new ADE7953PowerMeter(1, s_ade7953, 1));
  if (!(st = pm1->Init()).ok()) return st;
  std::unique_ptr<PowerMeter> pm2(new ADE7953PowerMeter(2, s_ade7953, 0));
  if (!(st = pm2->Init()).ok()) return st;

  pms->emplace_back(std::move(pm1));
  pms->emplace_back(std::move(pm2));

mgos_gpio_setup_input(36, MGOS_GPIO_PULL_NONE);
// or gpio 27 on hardware revision v0.1.9
//mgos_gpio_setup_input(27, MGOS_GPIO_PULL_NONE);
`

**Comment by lucassite120** [comment] 2023-12-19 15:27
> did anyone try this already? Flash New Shelly Plus 2PM for Apple HomeKit by OTA: https://www.youtube.com/watch?v=1VA9xkROlQc&ab_channel=RavenSystem

I followed these steps to flash Shelly for Homekit and it worked from https://www.youtube.com/watch?v=tXkaTqY86cc

**Comment by hughfr4nc15** [comment] 2024-01-16 22:20
> > did anyone try this already? Flash New Shelly Plus 2PM for Apple HomeKit by OTA: https://www.youtube.com/watch?v=1VA9xkROlQc&ab_channel=RavenSystem
> 
> I followed these steps to flash Shelly for Homekit and it worked from https://www.youtube.com/watch?v=tXkaTqY86cc

Anyone else tried this?

**Comment by bqueir0s** [comment] 2024-02-20 13:08
Still no update on this?

**Comment by hejsiri** [comment] 2024-02-23 20:21
@NS-K Do you think there is a chance to add support for Shelly 2PM?

**Comment by TibsD** [comment] 2024-03-08 13:51
Any news on this from the developers? The HAA alternative does not attract me a lot.

**Comment by lucassite120** [comment] 2024-04-06 08:36
> Any news on this from the developers? The HAA alternative does not attract me a lot.

OTA flashing HAA Homekit firmware now is very easy:
https://github.com/RavenSystem/mgos32toHAA?tab=readme-ov-file#shelly-convert-to-haa

**Comment by hughfr4nc15** [comment] 2024-04-06 08:56
> > Any news on this from the developers? The HAA alternative does not attract me a lot.
> 
> 
> 
> OTA flashing HAA Homekit firmware now is very easy:
> 
> https://github.com/RavenSystem/mgos32toHAA?tab=readme-ov-file#shelly-convert-to-haa

Haven't tried this one yet. Why don't you like it?

**Comment by lucassite120** [comment] 2024-04-06 17:06
> > OTA flashing HAA Homekit firmware now is very easy:
> > https://github.com/RavenSystem/mgos32toHAA?tab=readme-ov-file#shelly-convert-to-haa
> 
> Haven't tried this one yet. Do you like it? Does it work well?

Yes. I'm moving all my Shelly to HAA. Beginning is a bit complex, but it's awesome!! It has a great community support to solve any question.

**Comment by hughfr4nc15** [comment] 2024-04-06 19:39
I'm curious. :) Will give it a try.
Have been using Homebridge for the 2PM's.

**Comment by lucassite120** [comment] 2024-04-07 10:19
Try it. HAA works like a charm. You have a new video with subs explaining all process.
https://www.youtube.com/watch?v=06YHkRkwJE4

**Comment by dodvip123** [comment] 2024-04-08 12:11
> Try it. HAA works like a charm. You have a new video with subs explaining all process. https://www.youtube.com/watch?v=06YHkRkwJE4

Thanks, very good to know it works well!

**Comment by Alcor72** [comment] 2024-04-11 07:33
> > Try it. HAA works like a charm. You have a new video with subs explaining all process. https://www.youtube.com/watch?v=06YHkRkwJE4
> 
> Thanks, very good to know it works well!

Yep it works well... but... after using the mongoose's firmware... it looks like you're back in the 80's... :-) 
Biggest issue for me is the autocalibration which is not possible.
Anyway... keep waiting.

A recall as it was said previously... no need of ability to flash back units (when it is easy and works well... you just forget the equipment...since it breaks down...)

**Comment by hughfr4nc15** [comment] 2024-04-11 08:44
> Yep it works well... but... after using the mongoose's firmware... it looks like you're back in the 80's... :-) 
> 
> Biggest issue for me is the autocalibration which is not possible.
> 
> Anyway... keep waiting.
> 
> 
> 
> A recall as it was said previously... no need of ability to flash back units (when it is easy and works well... you just forget the equipment...since it breaks down...)

This was exactly what kinda made me wait a little bit more. 🙂
I'm running mongoose on the older models and Homebridge Plugin on the 2PM's.

**Comment by Alcor72** [comment] 2024-04-11 09:03
> 
> This was exactly what kinda made me wait a little bit more. 🙂 I'm running mongoose on the older models and Homebridge Plugin on the 2PM's.
Did you manage to get the 2PM's runing as window covers instead of windows? I am strugglin a bit with this with the homebridge pluggin.

**Comment by hughfr4nc15** [comment] 2024-04-11 09:35
> Did you manage to get the 2PM's runing as window covers instead of windows? I am strugglin a bit with this with the homebridge pluggin.

Yes, since I started using it it's been fine apart from the known "issues" like if you change the cover position in the wall button it will show as "Opening..." or "Closing..." indefinitely until you change it via Siri or Homekit. Apart from that... all good.

Here's an example of a device configuration in my Homebridge config:

`                {
                    "id": "ShellyPlus2PM-5341C28ER834",
                    "name": "Whatever-Shade",
                    "exclude": false,
                    "hostname": "192.168.1.100",
                    "switch:0": {
                        "exclude": true,
                        "type": "switch"
                    },
                    "switch:1": {
                        "exclude": true,
                        "type": "switch"
                    },
                    "switch:2": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "switch:3": {
                        "exclude": false,
                        "type": "switch"
                    },
                    "cover:0": {
                        "exclude": false,
                        "type": "windowCovering"
                    }
                },`

Hope it helps.

**Comment by markirb** [comment] 2024-05-20 18:27
> Any news on this from the developers? The HAA alternative does not attract me a lot.

I tried running this today on my 2PM. Still some issues see PR, but basic functionality seems to be working on mine (on latest HW).

If anyone wants to help and has UART access: A dump of the flash with esptool might be helpful to fix some of the remaining problems.

br

**Comment by markirb** [comment] 2024-05-23 20:38
I can only say that downgrade does not work. 

My current suspect is stock firmware not shipping conf0.json in default OTA and we override it. One can suspect that therein lies the information to discern the two hardware versions with their different pinout. And most likely the stock fw does not boot when there is no (correct?) information.

Again: A complete dump of an original Shelly2PM via esptool would be very helpful. I have only a flashed 2PM and cannot access this information any longer.

**Comment by markirb** [comment] 2024-06-07 19:45
Hi,

there is some good news: Downgrade is finally possible, as is detection of revision (https://github.com/mongoose-os-apps/shelly-homekit/pull/1388).
PM calibration values can be read but currently non calibrated are better.

So here is the first beta2 to test for you guys. Use at your own risk.(on a Mac please only use right click for download otherwise zip is extracted)
[shelly-homekit-ShellyPlus2PM.zip](https://github.com/user-attachments/files/15744196/shelly-homekit-ShellyPlus2PM.zip)


This was quite some work...
If you enjoy and use it please consider a donation to Timon (https://paypal.me/timoschilling) or me (https://www.paypal.com/donate/?hosted_button_id=RVFA9G5VMXRX8) to cover for hardware and hours lost along the way.


br

**Comment by devaccount89** [comment] 2024-06-13 10:31
Question: What is with the auto-calibration for window covers? if you use the Home Kit firmware is this not needed anymore? 
Thank you. 
br

**Comment by freswa** [comment] 2024-06-13 10:58
@devaccount89 I can calibrate the covers just fine. What are you missing?

**Comment by devaccount89** [comment] 2024-06-13 12:01
@freswa Ah yes. Sorry- saw the option just appearing once I switched the mode 👍 
Thank you!

**Comment by Mayoor7** [comment] 2024-06-13 15:19
Sorry, I'm new to Homekit and Hoobs. Are there any instructions on how to add the files from your zip file @markirb into Hombridge/Hoobs? Thanks for your work!

**Comment by freswa** [comment] 2024-06-13 15:28
@Mayoor7 See the README. Don't extract the zip, but upload it as a firmware file in the stock ui.

**Comment by roonie** [comment] 2024-06-26 07:41
I have now installed beta 5 on my Shelly. This went pretty smoothly and works as expected. Calibration also works fine. 

However, I ran into 1 thing and that is that the manual shutter control now works differently. Previously I could turn the knob to the open or close position and then when I released the knob, the shutter would stop. Now it keeps going until I turn it in the opposite direction. So it keeps closing until I turned the knob to the open position and then the shutter stops. Then I have to turn it to neutral and back to open to get it to open. This is not much of a problem, but does deviate from how the shelly software works.

**Comment by freswa** [comment] 2024-06-26 07:43
@roonie Set the Input mode to "Separate - toggle" and try again.

**Comment by roonie** [comment] 2024-06-26 07:48
@freswa Cool, that works. Thanks for the quick response.

**Comment by itai25** [comment] 2024-06-26 20:29
just installed two new shelly plus 2pm to control lights and installed beta 5 but they both have a very slow response time from homekit, one is around 2-3 seconds but the other is 10-20 and sometimes doesn't even change state.
both have near instant response from the web portal and its just via homekit. anyone else experiencing this?

**Closed** 2024-07-22 19:25 UTC
Labels: new-device-support
