### ISSUE TITLE
RGBW2 - AC Switch unsupported

### ISSUE THREAD

**Issue by Swq91** [mongoose-os-apps/shelly-homekit#1360] opened 2024-01-14 22:44 UTC
Hello!
I found issue with my RGBW2 on Mongoose OS (White Mode). When I connect item which is included separately in Shelly RGBW2 package (to use with AC Switch only) and provide 230V by it - LED strip starts blinking like a crazy. Switching with DC Switch (so in reality - short circuit between GND and I) works 100% ok. 
Moreover - AC Switch works correctly on original Shelly firmware.

**Comment by timoschilling** [comment] 2024-01-18 19:01
There are multiple reasons for that issue. 
1. the Shelly AC/DC adapter isn’t stable, he produces a flickering signal (that’s why the RGBW2 flickers)
2. The original firmware fixes that via software
3. We don’t fix it because it’s to complicated and would need a big refactoring / rewrite of the pwm system 
4. Not may users have this problem, most users are using a 12v or no switch
5. The source of the problem is the AC/DC adapter. So that’s should be fixed

If you google, you will find a hardware fix

**Closed by timoschilling** 2024-01-18 19:01 UTC
