### ISSUE TITLE
2.12.1: Shelly Plug S: Configuration is not retained

### ISSUE THREAD

**Issue by klix** [mongoose-os-apps/shelly-homekit#1423] opened 2024-07-20 14:18 UTC
Device: Plug S
Version: 2.12.1 (2.11.2 works as expected)

After upgrading to 2.12.1, device starts to AP fallback mode. Setting WiFi SSDs works and the device connects to the network. However, after cycling power the device has lost its configuration and starts to AP mode again.

I lack understanding of the source code, but commit 3d535f0 contains a change in mos.yml:567 that at first glance looks unrelated to other changes of the that commit and which could affect Plug S operation. Might be a valid change though.

**Comment by markirb** [comment] 2024-07-20 14:22
Yes that’s right. The change was intended for Plus Plug S. And leads to that behavior.

will be fixed in next release

**Comment by janjanson84** [comment] 2024-07-31 19:19
+1 Im experiencing the same bug, which is a bit odd, because i have several shelly plug s around. Hoping that no blackout occurs ;)

**Comment by zobe123** [comment] 2024-08-10 07:36
Hi everyone,

I’ve just encountered the same issue after updating my Shelly Plug S to version 2.12.1. The device loses its configuration and falls back to AP mode after a power cycle. I see that this is a known issue. Is there a timeline for the fix, or any workarounds I can use in the meantime?

Thanks!

**Comment by markirb** [comment] 2024-08-11 20:23
You can go back to 2.11 until next version is released

**Comment by pungd** [comment] 2024-08-11 22:40
> You can go back to 2.11 until next version is released

MIght be a stupid question, but where can I find the files/links to older firmware versions? I struggle with the same issue and wasn´t able to find them. Thanks!

**Comment by BlancoDeMallloca** [comment] 2024-08-12 04:38
They are listed in the release section. Just scroll down and you will find the previous releases. 

https://github.com/mongoose-os-apps/shelly-homekit/releases

**Comment by pungd** [comment] 2024-08-12 08:57
Awesome, thank you!

**Comment by KumanduS** [comment] 2024-08-19 22:32
Same problem here for my 2 Shelly Plug S. Is there a prevision of the date for the next version release? Is it possible to add the functionality to save configurations?

**Comment by markirb** [comment] 2024-09-12 18:43
fixed in current release

**Closed by markirb** 2024-09-12 18:43 UTC
Labels: confirmed-bug
