### ISSUE TITLE
Password protected GUI

### ISSUE THREAD

**Issue by trendchiller** [mongoose-os-apps/shelly-homekit#446] opened 2021-01-28 06:18 UTC
Hi,
This comes as a feature request:
It would be great to have an option to password protect the GUI. 
Son grabs the IP scanner and starts playing 😳

**Comment by timoschilling** [comment] 2021-01-28 08:31
duplicate of #82

**Comment by andyblac** [comment] 2021-01-28 09:20
thanks @timoschilling

**Closed by andyblac** 2021-01-28 09:20 UTC
Labels: duplicate
