### ISSUE TITLE
Garage opener status not working in HomeKit automation

### ISSUE THREAD

**Issue by mac-alx** [mongoose-os-apps/shelly-homekit#207] opened 2020-10-18 18:51 UTC
Hello,
the new garage opener function is great!

When creating an automation with shortcuts the automation will not work when pulling a request on the door status. 

Example:
12:00
If garage door is open
  Then
      Light on

The automation will work if you start it manually, but not automatically at a specified time. 

The automation will terminate as soon as it comes to a request on the Shelly. 

My IOS is the latest iOS 14 and Shelly FW is 2.3.1. 

Many greetings
Marc

**Comment by rojer** [comment] 2020-10-18 19:18
i tested this and could not reproduce.
i created automation that tied a light to status of garage door. i used "at night" instead of specific time, that's the only difference.
but otherwise, it worked - when door opens, light turns on (via automation), when door closes, light turns off.

**Comment by rojer** [comment] 2020-10-18 19:18
using ipad mini with ios 13 as hub.

**Comment by mac-alx** [comment] 2020-10-18 19:57
My hub is an Apple TV 4K. 

I do not have an automation on an open event but time triggered. 

Example which works:
18:00

Shortcut

light 1 on
If garage door current state is open
   Light 2 on
End if

Result: light 1 turns on, light 2 not. The script ends as soon as you put a request on garage door current state. 

Did you do the automation with or without shortcuts? I only have the problems when using shortcuts 

(See pic, sorry but my iOS is German)

![B0A05BE7-8487-461D-85D7-588AD3930057](https://user-images.githubusercontent.com/73077204/96378548-ed581b00-118c-11eb-855d-3d895266e767.jpeg)

**Comment by mac-alx** [comment] 2020-10-18 19:58
The automation above will work if you start it manually, but not at 18:00

**Comment by mac-alx** [comment] 2020-10-18 20:06
I just testet your automation:
When creating it without the Shortcut script ist works. 

(What I want to have at the end is an alert at 8 pm via pushcut if the door is open.  => the light was just to test the function)

**Comment by rojer** [comment] 2020-10-18 20:09
this seems like an ios bug. it really makes no difference to the device whether there's a shortcut in home app or not.

**Comment by mac-alx** [comment] 2020-10-18 20:32
Could you recreate that behaviour? Just to know if it is (another) iOS 14 bug?

Right now I do not have that with other devices. The same automation works eg with an eve door sensor.

**Comment by mac-alx** [comment] 2020-10-20 17:53
Update:
Did an update to tvos 14.2 Beta. 
HomeKit works more stabile concerning time triggered automations but still the same behaviour when starting an automation which checks the state of the garage door.

**Comment by Pixel-Chris** [comment] 2020-10-22 11:25
I have the same problem, but only with the garage door.
But when I click on „test this automation“ it works.
I configured an other Shelly to detached and use the double press function for my automation.
If garaged door is closed
  open it
Else
 close it.

„Test Automation“ works. 

The double click is recognised in HomeKit (I can see it), but the automation is not started !?

**Comment by andyblac** [comment] 2020-10-22 11:54
are you doing it with "Convert to shortcut"?

**Comment by andyblac** [comment] 2020-10-22 11:56
i have same issue y Alarm system, it is not a firmware issue, it is a HomeKit issue, try seting up with the a 3rd party app and 2 Events.

see here.
https://www.reddit.com/r/HomeKit/comments/jf9yrt/stateless_buttons_and_security_state/

**Comment by Pixel-Chris** [comment] 2020-10-22 12:01
Ok I will test it later! Thanks for that information

**Comment by andyblac** [comment] 2020-10-22 12:02
i also use "a convert to shortcut" with IF's for my shades, that one works no problem, it appears some event triggers in HomeKit are not working correctly

**Comment by andyblac** [comment] 2020-10-22 12:05
just for info:
![IMG_0356](https://user-images.githubusercontent.com/77936/96869335-3a770e00-1467-11eb-8602-092b54459062.jpeg)
![IMG_0355](https://user-images.githubusercontent.com/77936/96869340-3ba83b00-1467-11eb-8b50-74dd9330e028.jpeg)

**Comment by mac-alx** [comment] 2020-10-22 18:52
The idea of Andyblac got me to get it work!
First I made an automation in the eve app.

trigger: timestamp e.g. 20:00
condition: garage door is open
scene: any scene, does not matter which one

The switch to the HomeKit app and open the automation created in the eve app
Now you can see the if-statement "20:00 only if garage door is open"

Go into the action menu and deactivate the scene and active "convert to shortcut".
Here I inserted the url  of a pushcut notification (URL function with the pushcut adress) and the function "get contents of url".

Now as the if-rule is no more in the shortcut but in the trigger-rule of the automation everything works and I get a notification at 20:00 if the garage door is open.

Thanks a lot for the idea!

**Comment by andyblac** [comment] 2020-10-30 15:54
i'll close this now, reopen if you think you still have an issue.

**Closed by andyblac** 2020-10-30 15:54 UTC
